name: CI
on:
  # Only run when merging to master, or open/synchronize/reopen a PR.
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    - name: mdBook Action
      uses: peaceiris/actions-mdbook@v1.1.8

