name: CI
on:
  # Only run when merging to master, or open/synchronize/reopen a PR.
  push:
    branches:
      - master
  pull_request:

  - name: mdBook Action
    uses: peaceiris/actions-mdbook@v1.1.8
    with:
    # The mdBook version to download (if necessary) and use. Example: 0.3.5
    mdbook-version: 0.3.5 # optional, default is latest

