name: CI
on:
  # Only run when merging to master, or open/synchronize/reopen a PR.
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [stable]
        include:
          - build: stable
            os: ubuntu-latest
            rust: stable
          
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: bash ci/install-rust.sh ${{ matrix.rust }}
    - name: Build and run tests
      run: cargo test
    - name: Test no default
      run: cargo test --no-default-features
    - name: mdBook Action
      uses: peaceiris/actions-mdbook@v1.1.8

